name: NationCore
version: '${version}'
main: dev.thebjoredcraft.nationcore.NationCore
api-version: '1.20'
commands:
  bbar:
    permission: nations.cmd.bbar
  death:
    permission: nations.cmd.death
  rules:
  spawn:
    permission: nations.cmd.spawn
  tpadeny:
    permission: nations.cmd.tpadeny
  tpa:
    permission: nations.cmd.tpa
  tpaaccept:
    permission: nations.cmd.tpaaccept
  convertmoney:
    aliases:
      - cmoney
      - cm
    permission: nations.cmd.convertmoney
  money:
    permission: nations.cmd.money
  shop:
    permission: nations.cmd.shop
  alerttoggle:
    permission: nations.cmd.alerttoggle
  snations:
    permission: nations.cmd.snations
